<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Input Absensi — SMK Wira Cipta Karya</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="min-h-screen bg-[#f8f7f2] text-[#17243f]">
    <div class="flex min-h-screen">
        @include('partials.sidebar')
        <main class="min-w-0 flex-1">
            <header class="border-b border-[#17243f]/10 bg-[#f3f4f6]"><div class="mx-auto max-w-7xl px-6 py-4"><p class="text-sm text-slate-500">Kehadiran</p><h1 class="text-xl font-bold">Input Absensi</h1></div></header>
            <div class="mx-auto max-w-7xl space-y-6 px-6 py-10">
                <section class="rounded-2xl border border-[#17243f]/10 bg-[#f3f4f6] p-6 shadow-sm"><div class="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h2 class="text-lg font-bold">Jadwal Berikutnya</h2><p class="mt-1 text-sm text-slate-500">Jadwal terdekat yang dapat kamu siapkan.</p></div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Waktu WIB</p></div>@if ($nextSchedule)<a href="{{ route('attendances.create', ['schedule_id' => $nextSchedule->id, 'date' => $nextSchedule->next_start->toDateString()]) }}" class="mt-5 flex flex-col gap-3 rounded-xl border border-[#17243f]/10 bg-white p-4 transition hover:border-[#f5b63f] sm:flex-row sm:items-center sm:justify-between"><div><p class="font-bold">{{ $nextSchedule->subject }}</p><p class="mt-1 text-sm text-slate-500">{{ $nextSchedule->classRoom->nama_kelas }} · {{ $nextSchedule->teacher->nama }}</p></div><div class="text-left sm:text-right"><p class="font-semibold">{{ ['Sunday'=>'Minggu','Monday'=>'Senin','Tuesday'=>'Selasa','Wednesday'=>'Rabu','Thursday'=>'Kamis','Friday'=>'Jumat','Saturday'=>'Sabtu'][$nextSchedule->next_start->format('l')] }}</p><p class="text-sm text-slate-500">{{ $nextSchedule->next_start->format('d/m/Y H:i') }} WIB</p></div></a>@else<p class="mt-5 rounded-xl border border-dashed border-[#17243f]/15 bg-white p-5 text-sm text-slate-500">Belum ada jadwal berikutnya.</p>@endif</section>
                <section class="rounded-2xl border border-[#17243f]/10 bg-[#f3f4f6] p-6 shadow-sm"><div class="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h2 class="text-lg font-bold">Status Absensi Hari Ini</h2><p class="mt-1 text-sm text-slate-500">{{ $now->format('d/m/Y') }} · {{ $now->format('H:i') }} WIB</p></div><a href="{{ route('attendances.index') }}" class="text-sm font-semibold text-[#17243f] hover:underline">Refresh</a></div>@if ($todaySchedules->isEmpty())<p class="mt-5 rounded-xl border border-dashed border-[#17243f]/15 bg-white p-5 text-sm text-slate-500">Tidak ada jadwal pada hari ini.</p>@else<div class="mt-5 overflow-x-auto rounded-xl border border-[#17243f]/10 bg-white"><table class="min-w-full divide-y divide-[#17243f]/10"><thead class="bg-[#e5e7eb]"><tr><th class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Jam</th><th class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Mata Pelajaran</th><th class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Kelas</th><th class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Status</th><th class="px-4 py-3 text-right text-xs font-semibold uppercase tracking-wide text-slate-500">Aksi</th></tr></thead><tbody class="divide-y divide-[#17243f]/10">@foreach ($todaySchedules as $schedule)<tr class="hover:bg-[#f8f7f2]"><td class="px-4 py-3 text-sm font-semibold">{{ substr($schedule->start_time, 0, 5) }} - {{ substr($schedule->end_time, 0, 5) }}<span class="block text-xs font-normal text-slate-500">WIB</span></td><td class="px-4 py-3 text-sm font-medium">{{ $schedule->subject }}</td><td class="px-4 py-3 text-sm">{{ $schedule->classRoom->nama_kelas }}</td><td class="px-4 py-3 text-sm"><span class="inline-flex rounded-full px-3 py-1 text-xs font-semibold {{ $schedule->attendance_status === 'Sudah diabsen' ? 'bg-emerald-100 text-emerald-700' : ($schedule->attendance_status === 'Input terlambat' ? 'bg-amber-100 text-amber-700' : 'bg-slate-200 text-slate-600') }}">{{ $schedule->attendance_status }}</span>@if ($schedule->attendance_count > 0)<span class="mt-1 block text-xs text-slate-500">{{ $schedule->attendance_count }}/{{ $schedule->classRoom->students->count() }} siswa</span>@endif</td><td class="px-4 py-3 text-right"><a href="{{ route('attendances.create', ['schedule_id' => $schedule->id, 'date' => $today]) }}" class="rounded-lg border border-[#17243f]/15 bg-white px-3 py-1.5 text-xs font-semibold hover:bg-[#e5e7eb]">{{ $schedule->attendance_count > 0 ? 'Lihat / Edit' : 'Isi Absensi' }}</a></td></tr>@endforeach</tbody></table></div>@endif</section>
                <section class="rounded-2xl border border-[#17243f]/10 bg-[#f3f4f6] p-6 shadow-sm"><h2 class="text-lg font-bold">Pilih Jadwal Lain</h2><form method="GET" action="{{ route('attendances.create') }}" class="mt-5 grid gap-4 md:grid-cols-[1fr_1fr_auto] md:items-end"><div><label for="date" class="mb-2 block text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Tanggal</label><input id="date" name="date" type="date" value="{{ $selectedDate }}" required class="w-full rounded-xl border border-[#17243f]/10 bg-white px-4 py-3 text-sm"></div><div><label for="schedule_id" class="mb-2 block text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Jadwal Pelajaran</label><select id="schedule_id" name="schedule_id" required class="w-full rounded-xl border border-[#17243f]/10 bg-white px-4 py-3 text-sm"><option value="">Pilih jadwal</option>@foreach ($schedules as $item)<option value="{{ $item->id }}">{{ $item->day }} {{ substr($item->start_time, 0, 5) }} - {{ substr($item->end_time, 0, 5) }} · {{ $item->classRoom->nama_kelas }} · {{ $item->subject }}</option>@endforeach</select></div><button type="submit" class="rounded-xl bg-black px-5 py-3 text-sm font-semibold text-white hover:bg-slate-800">Buka Absensi</button></form></section>
            </div>
        </main>
    </div>
</body>
</html>
