<!DOCTYPE html>
<html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Jadwal Pelajaran — SMK Wira Cipta Karya</title><script src="https://cdn.tailwindcss.com"></script></head><body class="min-h-screen bg-[#f8f7f2] text-[#17243f]"><div class="flex min-h-screen">@include('partials.sidebar')<main class="min-w-0 flex-1"><header class="border-b border-[#17243f]/10 bg-[#f3f4f6]"><div class="mx-auto flex max-w-7xl items-center justify-between gap-4 px-6 py-4"><div><p class="text-sm text-slate-500">Pembelajaran</p><h1 class="text-xl font-bold">Jadwal Pelajaran</h1></div><a href="{{ route('schedules.create') }}" class="rounded-full bg-black px-4 py-2 text-sm font-semibold text-white hover:bg-slate-800">+ Tambah Jadwal</a></div></header><div class="mx-auto max-w-7xl px-6 py-10">
@if (session('success'))<div class="mb-6 rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-700">{{ session('success') }}</div>@endif
<form method="GET" action="{{ route('schedules.index') }}" class="mb-6 grid gap-3 rounded-2xl border border-[#17243f]/10 bg-[#f3f4f6] p-4 shadow-sm md:grid-cols-[1fr_1fr_1fr_auto]"><div><label for="academic_year_id" class="mb-2 block text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Tahun Ajaran</label><select id="academic_year_id" name="academic_year_id" class="w-full rounded-xl border border-[#17243f]/10 bg-white px-4 py-3 text-sm"><option value="">Semua Tahun</option>@foreach ($academicYears as $academicYear)<option value="{{ $academicYear->id }}" {{ (string) $academicYearId === (string) $academicYear->id ? 'selected' : '' }}>{{ $academicYear->tahun }} - {{ $academicYear->semester }}</option>@endforeach</select></div><div><label for="day" class="mb-2 block text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Hari</label><select id="day" name="day" class="w-full rounded-xl border border-[#17243f]/10 bg-white px-4 py-3 text-sm"><option value="">Semua Hari</option>@foreach (['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'] as $option)<option value="{{ $option }}" {{ $day === $option ? 'selected' : '' }}>{{ $option }}</option>@endforeach</select></div><div><label for="class_id" class="mb-2 block text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Kelas</label><select id="class_id" name="class_id" class="w-full rounded-xl border border-[#17243f]/10 bg-white px-4 py-3 text-sm"><option value="">Semua Kelas</option>@foreach ($classes as $class)<option value="{{ $class->id }}" {{ (string) $classId === (string) $class->id ? 'selected' : '' }}>{{ $class->nama_kelas }}</option>@endforeach</select></div><button type="submit" class="rounded-xl bg-black px-5 py-3 text-sm font-semibold text-white hover:bg-slate-800">Tampilkan</button></form>
@if ($schedules->isEmpty())<div class="rounded-2xl border border-dashed border-[#17243f]/15 bg-[#f3f4f6] p-8 text-center text-sm text-slate-500">Belum ada jadwal pelajaran.</div>@else<div class="overflow-hidden rounded-2xl border border-[#17243f]/10 bg-[#f3f4f6] shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-[#17243f]/10"><thead class="bg-[#e5e7eb]"><tr><th class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Hari / Jam</th><th class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Mata Pelajaran</th><th class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Kelas</th><th class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">Guru</th><th class="px-4 py-3 text-right text-xs font-semibold uppercase tracking-wide text-slate-500">Aksi</th></tr></thead><tbody class="divide-y divide-[#17243f]/10">@foreach ($schedules as $schedule)<tr class="hover:bg-white/60"><td class="px-4 py-3 text-sm"><span class="font-semibold">{{ $schedule->day }}</span><span class="block text-xs text-slate-500">{{ substr($schedule->start_time, 0, 5) }} - {{ substr($schedule->end_time, 0, 5) }}</span></td><td class="px-4 py-3 text-sm font-medium">{{ $schedule->subject }}<span class="block text-xs text-slate-500">{{ $schedule->academicYear->tahun }} / {{ $schedule->academicYear->semester }}</span></td><td class="px-4 py-3 text-sm">{{ $schedule->classRoom->nama_kelas }}</td><td class="px-4 py-3 text-sm">{{ $schedule->teacher->nama }}</td><td class="px-4 py-3 text-right"><div class="flex justify-end gap-2"><a href="{{ route('schedules.edit', $schedule) }}" class="rounded-lg border border-amber-300 bg-amber-50 px-3 py-1.5 text-xs font-semibold hover:bg-amber-100">Edit</a><x-delete :action="route('schedules.destroy', $schedule)" :name="$schedule->subject . ' - ' . $schedule->classRoom->nama_kelas" /></div></td></tr>@endforeach</tbody></table></div></div>@endif</div></main></div>
<script>
	const scheduleFilterForm = document.querySelector('form[action="{{ route('schedules.index') }}"]');
	const scheduleAcademicYear = document.getElementById('academic_year_id');
	const scheduleDay = document.getElementById('day');
	const scheduleClass = document.getElementById('class_id');

	[scheduleAcademicYear, scheduleDay, scheduleClass].forEach((select) => {
		select?.addEventListener('change', () => scheduleFilterForm?.requestSubmit());
	});
</script>
</body></html>
